### ISSUE TITLE
[zootr-sim] Lost Woods Adult Backwards Mido

### ISSUE THREAD

**Issue by philting** [scatter-dev/scatter.live#23]
In Lost Woods Adult, if coming from behind Mido then Saria's song is required for locations in front of Mido. However, that doesn't mean those locations aren't accessible. Currently if you exit to Lost Woods and then re-enter (like in the real game) it will work, but since this is a simulator I'd argue such measures are unnecessary.

**Comment by scatter-dev** [comment]
Yeah, so the reason it works that way is that the sim knows what subregion you're currently in and what locations and exits you can access from there. It works this way because that's how the actual randomizer's logic works, and it allows me to basically copy and paste all of it from there so that the sim works. So the sim knows you're behind Mido, can exit, and can then reenter, but without going around there's no way past Mido.

Anyway, you're right that it probably isn't necessary, but I'm hesitant to add an exception just for this since there are a few other places like this, plus I like the idea of it being closer to the real game in that it makes you leave and reenter, even if that ends up being more annoying than not. I'm also against changing the logic myself unless absolutely necessary purely out of fear I'd fuck something up.

I'm going to leave it the way it is *mostly* for consistency with how the sim works in other places.
