### ISSUE TITLE
Checking both the item and the hint in a grotto costs two bombchus with logic mode on

### ISSUE THREAD

**Issue by jontkane** [scatter-dev/scatter.live#9]
I'm not sure what the UI ought to be but you ought to be able to get both the hint and the item with a single chu for the generic grottos.

**Comment by scatter-dev** [comment]
Yeah, this is a weird one. Originally this wasn't an issue because the sim placed you in the subregion of each location whenever it was checked. This works in theory, but unfortunately there are quite a few exits in the randomizer logic that aren't bidirectional; mostly in dungeons, it seems. So you'd get stuck in a subregion with no way out other than (save)warping. I'm realizing now that I can have it only do that for grottos, as the grottos all seem to have exits leading out. I'll do that and hopefully no one will need to savewarp out of any grottos.
